name: CustomHunger
version: '${project.version}'
main: com.rmsca.customhunger.CustomHunger
description: A Minecraft plugin that lets you customize any food values
api-version: 1.18
author: RMSCA
website: https://github.com/RMSCA/Custom-Hunger
commands:
  ch:
    description: The main command of Custom Hunger
    usage: "Type \"/ch help\" for help"
    aliases: 
      - customhunger
